2021-03-19 15:35:52,620 [INFO]: Connecting to the Vicon...
2021-03-19 15:35:52,621 [INFO]: Connected to Vicon!
2021-03-19 15:35:52,621 [INFO]: Enabling data types...
2021-03-19 15:35:52,622 [DEBUG]: Segments: True
2021-03-19 15:35:52,622 [DEBUG]: Markers: True
2021-03-19 15:35:52,622 [DEBUG]: Unlabeled Markers: True
2021-03-19 15:35:52,622 [DEBUG]: Marker Rays: True
2021-03-19 15:35:52,622 [DEBUG]: Devices: True
2021-03-19 15:35:52,622 [DEBUG]: Centroids: True 
2021-03-19 15:35:52,622 [INFO]: Testing stream modes...
2021-03-19 15:35:52,622 [INFO]: Getting a frame in ClientPull mode...
2021-03-19 15:35:52,623 [DEBUG]: Fetched! Pulled frame number: 1866565
2021-03-19 15:35:52,623 [INFO]: Getting a frame in PreFetch mode...
2021-03-19 15:35:53,626 [INFO]: Getting a frame in ServerPush mode...
2021-03-19 15:35:53,627 [DEBUG]: Fetched! Pulled frame number: 1866657
2021-03-19 15:35:53,627 [INFO]: ServerPush mode set.
2021-03-19 15:35:53,627 [INFO]: Getting available framerates...
2021-03-19 15:35:53,627 [INFO]: Current Vicon frame rate: 100.0 Hz.
2021-03-19 15:35:53,627 [INFO]: Available frame rates: 
2021-03-19 15:35:53,627 [INFO]: Process Rate : 0 Hz 

2021-03-19 15:35:53,628 [INFO]: Setting axis...
2021-03-19 15:35:53,628 [INFO]: X Axis: AxisMapping.EForward
2021-03-19 15:35:53,628 [INFO]: Y Axis: AxisMapping.ELeft
2021-03-19 15:35:53,628 [INFO]: Z Axis: AxisMapping.EUp
2021-03-19 15:35:53,628 [INFO]: Initializing drivers...
2021-03-19 15:35:53,628 [INFO]: Drivers initialized.
2021-03-19 15:35:53,628 [INFO]: Connecting to the Crazyflie...
2021-03-19 15:35:53,628 [DEBUG]: Adding callback on port [6] to [<bound method Localization._incoming of <cflib.crazyflie.localization.Localization object at 0x000001847EF4E408>>]
2021-03-19 15:35:53,628 [DEBUG]: Adding callback on port [5] to [<bound method Log._new_packet_cb of <cflib.crazyflie.log.Log object at 0x000001847EF4E508>>]
2021-03-19 15:35:53,628 [DEBUG]: Adding callback on port [0] to [<bound method Console.incoming of <cflib.crazyflie.console.Console object at 0x000001847EF4E608>>]
2021-03-19 15:35:53,629 [DEBUG]: Adding callback on port [2] to [<bound method _ParamUpdater._new_packet_cb of <_ParamUpdater(Thread-7, initial daemon)>>]
2021-03-19 15:35:53,630 [DEBUG]: Adding callback on port [4] to [<bound method Memory._new_packet_cb of <cflib.crazyflie.mem.Memory object at 0x0000018475DF9C08>>]
2021-03-19 15:35:53,630 [DEBUG]: Adding callback on port [13] to [<bound method PlatformService._platform_callback of <cflib.crazyflie.platformservice.PlatformService object at 0x000001847EF4EC88>>]
2021-03-19 15:35:53,630 [DEBUG]: Adding callback on port [15] to [<bound method PlatformService._crt_service_callback of <cflib.crazyflie.platformservice.PlatformService object at 0x000001847EF4EC88>>]
2021-03-19 15:35:53,630 [INFO]: Crazyflie has the following segments: ['Crazyflie']
2021-03-19 15:35:53,630 [INFO]: Crazyflie has root: Crazyflie
2021-03-19 15:35:53,630 [DEBUG]: ===Checking functions without flying===
2021-03-19 15:35:53,630 [DEBUG]: Fetched! Pulled frame number: 1866665
2021-03-19 15:35:53,631 [DEBUG]: Drone rotation matrix from Vicon: (((0.9938059371438974, 0.07620825468581457, -0.08088300943512103), (-0.07863057811422072, 0.9965328578214628, -0.027193665946532043), (0.07853019472128725, 0.033385104461872865, 0.9963525697849666)), False)
2021-03-19 15:35:53,631 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02728644 -0.08097146 -0.07653346]
2021-03-19 15:35:53,631 [DEBUG]: Drone position from global origin: (-201.15242979328335, 145.3161713403119, 44.407724829032546)
2021-03-19 15:35:53,632 [DEBUG]: Fetched! Pulled frame number: 1866666
2021-03-19 15:35:53,632 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937843559021443, 0.07626948190943135, -0.0810901972708599), (-0.07869672046741584, 0.9965284018912887, -0.02716561082817081), (0.07873677763176153, 0.033378291646834535, 0.9963364941097488)), False)
2021-03-19 15:35:53,633 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02725874 -0.08117933 -0.07659636]
2021-03-19 15:35:53,633 [DEBUG]: Drone position from global origin: (-201.15576890141153, 145.3188202631843, 44.40270399136607)
2021-03-19 15:35:53,643 [DEBUG]: Fetched! Pulled frame number: 1866667
2021-03-19 15:35:53,643 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937873162811516, 0.07626108060111654, -0.08106181335410935), (-0.07869514344024288, 0.9965258294922126, -0.02726436417335686), (0.07870098091908419, 0.03347415033138007, 0.9963361063727271)), False)
2021-03-19 15:35:53,643 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.0273578  -0.08115085 -0.07658773]
2021-03-19 15:35:53,643 [DEBUG]: Drone position from global origin: (-201.1632608823253, 145.31947553677458, 44.40354865684063)
2021-03-19 15:35:53,652 [DEBUG]: Fetched! Pulled frame number: 1866668
2021-03-19 15:35:53,652 [DEBUG]: Drone rotation matrix from Vicon: (((0.9938061727664692, 0.07610760339309246, -0.08097483360293072), (-0.07854650510499255, 0.9965347107626715, -0.02736817094637211), (0.07861130648357116, 0.03355894740480111, 0.9963403331904354)), False)
2021-03-19 15:35:53,652 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02746179 -0.08106359 -0.07643275]
2021-03-19 15:35:53,652 [DEBUG]: Drone position from global origin: (-201.16779607956312, 145.32302635795426, 44.40078141741169)
2021-03-19 15:35:53,663 [DEBUG]: Fetched! Pulled frame number: 1866669
2021-03-19 15:35:53,663 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937814847215142, 0.07614151368624837, -0.0812454953721727), (-0.07857063078858546, 0.9965393779694072, -0.02712792166442028), (0.0788987744023104, 0.03334273608919921, 0.9963248693814178)), False)
2021-03-19 15:35:53,663 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02722126 -0.08133514 -0.07646857]
2021-03-19 15:35:53,663 [DEBUG]: Drone position from global origin: (-201.1728741095145, 145.32156627160302, 44.39849274430212)
2021-03-19 15:35:53,672 [DEBUG]: Fetched! Pulled frame number: 1866670
2021-03-19 15:35:53,673 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937964464235405, 0.07620410707694299, -0.08100343906618229), (-0.07861896445333945, 0.996537739139642, -0.027047974022748774), (0.07866181732090513, 0.03324858696330644, 0.9963467518694061)), False)
2021-03-19 15:35:53,673 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02714048 -0.08109229 -0.07653004]
2021-03-19 15:35:53,673 [DEBUG]: Drone position from global origin: (-201.17353390688328, 145.32918849460214, 44.39738666574869)
2021-03-19 15:35:53,682 [DEBUG]: Fetched! Pulled frame number: 1866671
2021-03-19 15:35:53,683 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937977686736826, 0.07616029361974272, -0.08102841881071154), (-0.07859832197956321, 0.9965316083391976, -0.027332350116463795), (0.07866574070843296, 0.03353152630952884, 0.9963369600602734)), False)
2021-03-19 15:35:53,683 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02742596 -0.08111735 -0.0764861 ]
2021-03-19 15:35:53,683 [DEBUG]: Drone position from global origin: (-201.17845359533095, 145.3284201171512, 44.40263561491065)
2021-03-19 15:35:53,692 [DEBUG]: Fetched! Pulled frame number: 1866672
2021-03-19 15:35:53,693 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937925653951238, 0.07611461470360886, -0.08113508731676862), (-0.0785613828800473, 0.9965326921743259, -0.0273989515814876), (0.07876830635067068, 0.033602959041002044, 0.9963264500445301)), False)
2021-03-19 15:35:53,693 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02749304 -0.08122437 -0.07644081]
2021-03-19 15:35:53,693 [DEBUG]: Drone position from global origin: (-201.1813188051313, 145.3319816655091, 44.40183128924871)
2021-03-19 15:35:53,702 [DEBUG]: Fetched! Pulled frame number: 1866673
2021-03-19 15:35:53,703 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937774522195212, 0.07604465454198654, -0.08138541623452597), (-0.07848629175333867, 0.9965432414227193, -0.027229946410332103), (0.07903339463092118, 0.03344814629078388, 0.9963106664303175)), False)
2021-03-19 15:35:53,703 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02732398 -0.08147553 -0.07637198]
2021-03-19 15:35:53,703 [DEBUG]: Drone position from global origin: (-201.18606970677644, 145.33079480666504, 44.40408406708751)
2021-03-19 15:35:53,712 [DEBUG]: Fetched! Pulled frame number: 1866674
2021-03-19 15:35:53,712 [DEBUG]: Drone rotation matrix from Vicon: (((0.9937795032565896, 0.07593039843909916, -0.08146700865973748), (-0.07837949528368113, 0.9965499135719044, -0.027293304653435813), (0.07911354894176788, 0.03350886976174372, 0.9963022643862298)), False)
2021-03-19 15:35:53,713 [DEBUG]: Drone Euler XYZ from Vicon as given: [ 0.02738775 -0.08155739 -0.07625752]
2021-03-19 15:35:53,713 [DEBUG]: Drone position from global origin: (-201.18605259079953, 145.33170747804013, 44.399711741387534)
2021-03-19 15:35:53,713 [DEBUG]: ===============Offline check done=================
2021-03-19 15:35:53,714 [DEBUG]: Adding callback on port [6] to [<bound method Localization._incoming of <cflib.crazyflie.localization.Localization object at 0x000001847EF4EDC8>>]
2021-03-19 15:35:53,714 [DEBUG]: Adding callback on port [5] to [<bound method Log._new_packet_cb of <cflib.crazyflie.log.Log object at 0x000001847EF65188>>]
2021-03-19 15:35:53,714 [DEBUG]: Adding callback on port [0] to [<bound method Console.incoming of <cflib.crazyflie.console.Console object at 0x000001847EF65488>>]
2021-03-19 15:35:53,714 [DEBUG]: Adding callback on port [2] to [<bound method _ParamUpdater._new_packet_cb of <_ParamUpdater(Thread-9, initial daemon)>>]
2021-03-19 15:35:53,715 [DEBUG]: Adding callback on port [4] to [<bound method Memory._new_packet_cb of <cflib.crazyflie.mem.Memory object at 0x000001847EF659C8>>]
2021-03-19 15:35:53,715 [DEBUG]: Adding callback on port [13] to [<bound method PlatformService._platform_callback of <cflib.crazyflie.platformservice.PlatformService object at 0x000001847EF65B08>>]
2021-03-19 15:35:53,715 [DEBUG]: Adding callback on port [15] to [<bound method PlatformService._crt_service_callback of <cflib.crazyflie.platformservice.PlatformService object at 0x000001847EF65B08>>]
2021-03-19 15:35:53,715 [INFO]: Callback->Connection initialized[radio://0/80/2M]
2021-03-19 15:35:53,721 [INFO]: We are connected[radio://0/80/2M], request connection setup
2021-03-19 15:35:53,722 [INFO]: Callback->Connected to [radio://0/80/2M]
2021-03-19 15:35:53,725 [WARNING]: Error no LogEntry to handle id=1
2021-03-19 15:35:53,726 [WARNING]: Error no LogEntry to handle id=2
2021-03-19 15:35:53,731 [INFO]: Protocol  version: 4
2021-03-19 15:35:53,735 [DEBUG]: Logging reset, continue with TOC download
2021-03-19 15:35:53,735 [DEBUG]: [5]: Using V2 protocol: 1
2021-03-19 15:35:53,735 [DEBUG]: [5]: Start fetching...
2021-03-19 15:35:53,735 [DEBUG]: Adding callback on port [5] to [<bound method TocFetcher._new_packet_cb of <cflib.crazyflie.toc.TocFetcher object at 0x000001847EF81CC8>>]
2021-03-19 15:35:53,739 [DEBUG]: [5]: Got TOC CRC, 317 items and crc=0x05C5AF70
2021-03-19 15:35:53,745 [INFO]: TOC for port [5] found in cache
2021-03-19 15:35:53,746 [DEBUG]: Removing callback on port [5] to [<bound method TocFetcher._new_packet_cb of <cflib.crazyflie.toc.TocFetcher object at 0x000001847EF81CC8>>]
2021-03-19 15:35:53,746 [DEBUG]: [5]: Done!
2021-03-19 15:35:53,746 [INFO]: Log TOC finished updating
2021-03-19 15:35:53,746 [DEBUG]: Requesting number of memories
2021-03-19 15:35:53,749 [INFO]: 9 memories found
2021-03-19 15:35:53,749 [DEBUG]: Requesting first id
2021-03-19 15:35:53,754 [DEBUG]: Requesting information about memory 1
2021-03-19 15:35:53,758 [DEBUG]: Memory: id=1, type=LED driver, size=24
2021-03-19 15:35:53,758 [DEBUG]: Requesting information about memory 2
2021-03-19 15:35:53,763 [DEBUG]: Memory: id=2, type=Loco Positioning, size=6144
2021-03-19 15:35:53,763 [DEBUG]: Requesting information about memory 3
2021-03-19 15:35:53,767 [DEBUG]: Memory: id=3, type=Trajectory, size=4096
2021-03-19 15:35:53,767 [DEBUG]: Requesting information about memory 4
2021-03-19 15:35:53,771 [DEBUG]: Memory: id=4, type=Loco Positioning 2, size=69632
2021-03-19 15:35:53,771 [DEBUG]: Requesting information about memory 5
2021-03-19 15:35:53,775 [DEBUG]: Memory: id=5, type=Lighthouse positioning, size=96
2021-03-19 15:35:53,775 [DEBUG]: Requesting information about memory 6
2021-03-19 15:35:53,779 [DEBUG]: Memory: id=6, type=Memory tester, size=4096
2021-03-19 15:35:53,779 [DEBUG]: Requesting information about memory 7
2021-03-19 15:35:53,783 [DEBUG]: Memory: id=7, type=Unknown, size=0
2021-03-19 15:35:53,784 [DEBUG]: Requesting information about memory 8
2021-03-19 15:35:53,788 [DEBUG]: Done getting all the memories, start reading the OWs
2021-03-19 15:35:53,788 [DEBUG]: Updating content of memory 8
2021-03-19 15:35:53,788 [DEBUG]: Requesting new chunk of 11bytes at 0x0
2021-03-19 15:35:53,793 [DEBUG]: READ: Mem=8, addr=0x0, status=0x0, data=(235, 12, 0, 0, 0, 188, 15, 205, 0, 12, 1)
2021-03-19 15:35:53,793 [DEBUG]: READING: We are still interested in request for mem 8
2021-03-19 15:35:53,793 [DEBUG]: Requesting new chunk of 15bytes at 0x8
2021-03-19 15:35:53,799 [DEBUG]: READ: Mem=8, addr=0x8, status=0x0, data=(0, 12, 1, 7, 98, 99, 70, 108, 111, 119, 50, 2, 1, 65, 84)
2021-03-19 15:35:53,799 [DEBUG]: READING: We are still interested in request for mem 8
2021-03-19 15:35:53,799 [DEBUG]: OW 0DD9203F00000040 (BC:0F): {'Board name': 'bcFlow2', 'Board revision': 'A'}
2021-03-19 15:35:53,800 [INFO]: Memories finished updating
2021-03-19 15:35:53,800 [DEBUG]: [2]: Using V2 protocol: 1
2021-03-19 15:35:53,800 [DEBUG]: [2]: Start fetching...
2021-03-19 15:35:53,800 [DEBUG]: Adding callback on port [2] to [<bound method TocFetcher._new_packet_cb of <cflib.crazyflie.toc.TocFetcher object at 0x000001847EFB3A48>>]
2021-03-19 15:35:53,811 [DEBUG]: [2]: Got TOC CRC, 164 items and crc=0x1042AFA8
2021-03-19 15:35:53,814 [INFO]: TOC for port [2] found in cache
2021-03-19 15:35:53,814 [DEBUG]: Removing callback on port [2] to [<bound method TocFetcher._new_packet_cb of <cflib.crazyflie.toc.TocFetcher object at 0x000001847EFB3A48>>]
2021-03-19 15:35:53,815 [DEBUG]: [2]: Done!
2021-03-19 15:35:53,815 [INFO]: Param TOC finished updating
2021-03-19 15:35:53,815 [INFO]: Callback->Connection setup finished [radio://0/80/2M]
2021-03-19 15:35:53,815 [DEBUG]: Requesting request to update param [6]
2021-03-19 15:35:53,815 [DEBUG]: Requesting request to update param [1]
2021-03-19 15:35:53,815 [DEBUG]: Requesting request to update param [2]
2021-03-19 15:35:53,815 [DEBUG]: Requesting request to update param [3]
2021-03-19 15:35:53,816 [DEBUG]: Requesting request to update param [4]
2021-03-19 15:35:53,816 [DEBUG]: Requesting request to update param [5]
2021-03-19 15:35:53,816 [DEBUG]: Requesting request to update param [7]
2021-03-19 15:35:53,817 [DEBUG]: Requesting request to update param [8]
2021-03-19 15:35:53,817 [DEBUG]: Requesting request to update param [9]
2021-03-19 15:35:53,818 [DEBUG]: Requesting request to update param [10]
2021-03-19 15:35:53,818 [DEBUG]: Requesting request to update param [11]
2021-03-19 15:35:53,818 [DEBUG]: Requesting request to update param [16]
2021-03-19 15:35:53,819 [DEBUG]: Requesting request to update param [12]
2021-03-19 15:35:53,819 [DEBUG]: Requesting request to update param [13]
2021-03-19 15:35:53,819 [DEBUG]: Requesting request to update param [14]
2021-03-19 15:35:53,820 [DEBUG]: Requesting request to update param [15]
2021-03-19 15:35:53,820 [DEBUG]: Requesting request to update param [17]
2021-03-19 15:35:53,820 [DEBUG]: Requesting request to update param [18]
2021-03-19 15:35:53,821 [DEBUG]: Requesting request to update param [19]
2021-03-19 15:35:53,821 [DEBUG]: Requesting request to update param [20]
2021-03-19 15:35:53,821 [DEBUG]: Requesting request to update param [21]
2021-03-19 15:35:53,822 [DEBUG]: Requesting request to update param [22]
2021-03-19 15:35:53,822 [DEBUG]: Requesting request to update param [23]
2021-03-19 15:35:53,822 [DEBUG]: Requesting request to update param [24]
2021-03-19 15:35:53,823 [DEBUG]: Requesting request to update param [25]
2021-03-19 15:35:53,823 [DEBUG]: Requesting request to update param [26]
2021-03-19 15:35:53,823 [DEBUG]: Requesting request to update param [27]
2021-03-19 15:35:53,824 [DEBUG]: Requesting request to update param [28]
2021-03-19 15:35:53,824 [DEBUG]: Requesting request to update param [29]
2021-03-19 15:35:53,824 [DEBUG]: Requesting request to update param [30]
2021-03-19 15:35:53,824 [DEBUG]: Requesting request to update param [31]
2021-03-19 15:35:53,824 [DEBUG]: Requesting request to update param [32]
2021-03-19 15:35:53,825 [DEBUG]: Requesting request to update param [33]
2021-03-19 15:35:53,825 [DEBUG]: Requesting request to update param [34]
2021-03-19 15:35:53,825 [DEBUG]: Requesting request to update param [35]
2021-03-19 15:35:53,825 [DEBUG]: Requesting request to update param [36]
2021-03-19 15:35:53,825 [DEBUG]: Requesting request to update param [37]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [38]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [39]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [40]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [41]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [42]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [43]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [44]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [45]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [46]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [47]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [48]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [49]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [50]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [51]
2021-03-19 15:35:53,826 [DEBUG]: Requesting request to update param [52]
2021-03-19 15:35:53,827 [DEBUG]: Requesting request to update param [53]
2021-03-19 15:35:53,827 [DEBUG]: Requesting request to update param [54]
2021-03-19 15:35:53,827 [DEBUG]: Requesting request to update param [55]
2021-03-19 15:35:53,827 [DEBUG]: Requesting request to update param [56]
2021-03-19 15:35:53,827 [DEBUG]: Requesting request to update param [57]
2021-03-19 15:35:53,828 [DEBUG]: Requesting request to update param [58]
2021-03-19 15:35:53,828 [DEBUG]: Requesting request to update param [59]
2021-03-19 15:35:53,828 [DEBUG]: Requesting request to update param [60]
2021-03-19 15:35:53,828 [DEBUG]: Requesting request to update param [61]
2021-03-19 15:35:53,828 [DEBUG]: Requesting request to update param [62]
2021-03-19 15:35:53,829 [DEBUG]: Requesting request to update param [63]
2021-03-19 15:35:53,829 [DEBUG]: Requesting request to update param [64]
2021-03-19 15:35:53,829 [DEBUG]: Requesting request to update param [65]
2021-03-19 15:35:53,829 [DEBUG]: Requesting request to update param [66]
2021-03-19 15:35:53,830 [DEBUG]: Requesting request to update param [67]
2021-03-19 15:35:53,830 [DEBUG]: Requesting request to update param [68]
2021-03-19 15:35:53,830 [DEBUG]: Requesting request to update param [69]
2021-03-19 15:35:53,831 [DEBUG]: Requesting request to update param [70]
2021-03-19 15:35:53,831 [DEBUG]: Requesting request to update param [71]
2021-03-19 15:35:53,831 [DEBUG]: Requesting request to update param [72]
2021-03-19 15:35:53,831 [DEBUG]: Requesting request to update param [73]
2021-03-19 15:35:53,832 [DEBUG]: Requesting request to update param [74]
2021-03-19 15:35:53,832 [DEBUG]: Requesting request to update param [75]
2021-03-19 15:35:53,832 [DEBUG]: Requesting request to update param [76]
2021-03-19 15:35:53,832 [DEBUG]: Requesting request to update param [77]
2021-03-19 15:35:53,833 [DEBUG]: Requesting request to update param [78]
2021-03-19 15:35:53,833 [DEBUG]: Requesting request to update param [79]
2021-03-19 15:35:53,833 [DEBUG]: Requesting request to update param [80]
2021-03-19 15:35:53,833 [DEBUG]: Requesting request to update param [81]
2021-03-19 15:35:53,833 [DEBUG]: Requesting request to update param [82]
2021-03-19 15:35:53,834 [DEBUG]: Requesting request to update param [83]
2021-03-19 15:35:53,834 [DEBUG]: Requesting request to update param [84]
2021-03-19 15:35:53,834 [DEBUG]: Requesting request to update param [85]
2021-03-19 15:35:53,834 [DEBUG]: Requesting request to update param [86]
2021-03-19 15:35:53,834 [DEBUG]: Requesting request to update param [87]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [88]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [89]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [90]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [91]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [92]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [93]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [94]
2021-03-19 15:35:53,835 [DEBUG]: Requesting request to update param [95]
2021-03-19 15:35:53,836 [DEBUG]: Requesting request to update param [96]
2021-03-19 15:35:53,836 [DEBUG]: Requesting request to update param [97]
2021-03-19 15:35:53,836 [DEBUG]: Requesting request to update param [98]
2021-03-19 15:35:53,836 [DEBUG]: Requesting request to update param [99]
2021-03-19 15:35:53,836 [DEBUG]: Requesting request to update param [100]
2021-03-19 15:35:53,837 [DEBUG]: Requesting request to update param [101]
2021-03-19 15:35:53,837 [DEBUG]: Requesting request to update param [102]
2021-03-19 15:35:53,837 [DEBUG]: Requesting request to update param [103]
2021-03-19 15:35:53,837 [DEBUG]: Requesting request to update param [104]
2021-03-19 15:35:53,837 [DEBUG]: Requesting request to update param [105]
2021-03-19 15:35:53,837 [DEBUG]: Requesting request to update param [106]
2021-03-19 15:35:53,837 [DEBUG]: Requesting request to update param [107]
2021-03-19 15:35:53,838 [DEBUG]: Requesting request to update param [108]
2021-03-19 15:35:53,838 [DEBUG]: Requesting request to update param [109]
2021-03-19 15:35:53,838 [DEBUG]: Requesting request to update param [110]
2021-03-19 15:35:53,838 [DEBUG]: Requesting request to update param [111]
2021-03-19 15:35:53,838 [DEBUG]: Requesting request to update param [112]
2021-03-19 15:35:53,838 [DEBUG]: Requesting request to update param [113]
2021-03-19 15:35:53,839 [DEBUG]: Requesting request to update param [114]
2021-03-19 15:35:53,839 [DEBUG]: Requesting request to update param [115]
2021-03-19 15:35:53,839 [DEBUG]: Requesting request to update param [116]
2021-03-19 15:35:53,840 [DEBUG]: Requesting request to update param [117]
2021-03-19 15:35:53,840 [DEBUG]: Requesting request to update param [118]
2021-03-19 15:35:53,840 [DEBUG]: Requesting request to update param [119]
2021-03-19 15:35:53,840 [DEBUG]: Requesting request to update param [120]
2021-03-19 15:35:53,841 [DEBUG]: Requesting request to update param [121]
2021-03-19 15:35:53,841 [DEBUG]: Requesting request to update param [122]
2021-03-19 15:35:53,841 [DEBUG]: Requesting request to update param [123]
2021-03-19 15:35:53,841 [DEBUG]: Requesting request to update param [124]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [125]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [126]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [127]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [128]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [140]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [141]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [142]
2021-03-19 15:35:53,842 [DEBUG]: Requesting request to update param [143]
2021-03-19 15:35:53,843 [DEBUG]: Requesting request to update param [145]
2021-03-19 15:35:53,843 [DEBUG]: Requesting request to update param [146]
2021-03-19 15:35:53,843 [DEBUG]: Requesting request to update param [147]
2021-03-19 15:35:53,843 [DEBUG]: Requesting request to update param [151]
2021-03-19 15:35:53,843 [DEBUG]: Requesting request to update param [152]
2021-03-19 15:35:53,844 [DEBUG]: Requesting request to update param [154]
2021-03-19 15:35:53,844 [DEBUG]: Requesting request to update param [155]
2021-03-19 15:35:53,844 [DEBUG]: Requesting request to update param [156]
2021-03-19 15:35:53,844 [DEBUG]: Requesting request to update param [129]
2021-03-19 15:35:53,844 [DEBUG]: Requesting request to update param [130]
2021-03-19 15:35:53,845 [DEBUG]: Requesting request to update param [131]
2021-03-19 15:35:53,845 [DEBUG]: Requesting request to update param [132]
2021-03-19 15:35:53,845 [DEBUG]: Requesting request to update param [133]
2021-03-19 15:35:53,845 [DEBUG]: Requesting request to update param [134]
2021-03-19 15:35:53,845 [DEBUG]: Requesting request to update param [135]
2021-03-19 15:35:53,845 [DEBUG]: Requesting request to update param [136]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [137]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [138]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [139]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [144]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [148]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [149]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [150]
2021-03-19 15:35:53,846 [DEBUG]: Requesting request to update param [153]
2021-03-19 15:35:53,847 [DEBUG]: Requesting request to update param [157]
2021-03-19 15:35:53,847 [DEBUG]: Requesting request to update param [158]
2021-03-19 15:35:53,847 [DEBUG]: Requesting request to update param [159]
2021-03-19 15:35:53,847 [DEBUG]: Requesting request to update param [160]
2021-03-19 15:35:53,847 [DEBUG]: Requesting request to update param [161]
2021-03-19 15:35:53,848 [DEBUG]: Requesting request to update param [162]
2021-03-19 15:35:53,848 [DEBUG]: Requesting request to update param [163]
2021-03-19 15:35:53,848 [DEBUG]: Updated parameter [imu_sensors.BMP388]
2021-03-19 15:35:53,853 [DEBUG]: Updated parameter [imu_sensors.HMC5883L]
2021-03-19 15:35:53,857 [DEBUG]: Updated parameter [imu_sensors.MS5611]
2021-03-19 15:35:53,860 [DEBUG]: Updated parameter [imu_tests.MPU6500]
2021-03-19 15:35:53,864 [DEBUG]: Updated parameter [imu_tests.HMC5883L]
2021-03-19 15:35:53,869 [DEBUG]: Updated parameter [imu_tests.MS5611]
2021-03-19 15:35:53,872 [DEBUG]: Updated parameter [cpu.flash]
2021-03-19 15:35:53,876 [DEBUG]: Updated parameter [cpu.id0]
2021-03-19 15:35:53,879 [DEBUG]: Updated parameter [cpu.id1]
2021-03-19 15:35:53,883 [DEBUG]: Updated parameter [cpu.id2]
2021-03-19 15:35:53,886 [DEBUG]: Updated parameter [system.selftestPassed]
2021-03-19 15:35:53,890 [DEBUG]: Updated parameter [system.taskDump]
2021-03-19 15:35:53,894 [DEBUG]: Updated parameter [sound.effect]
2021-03-19 15:35:53,899 [DEBUG]: Updated parameter [sound.neffect]
2021-03-19 15:35:53,902 [DEBUG]: Updated parameter [sound.freq]
2021-03-19 15:35:53,906 [DEBUG]: Updated parameter [sound.ratio]
2021-03-19 15:35:53,909 [DEBUG]: Updated parameter [memTst.resetW]
2021-03-19 15:35:53,913 [DEBUG]: Updated parameter [commander.enHighLevel]
2021-03-19 15:35:53,916 [DEBUG]: Updated parameter [flightmode.althold]
2021-03-19 15:35:53,920 [DEBUG]: Updated parameter [flightmode.poshold]
2021-03-19 15:35:53,925 [DEBUG]: Updated parameter [flightmode.posSet]
2021-03-19 15:35:53,937 [DEBUG]: Updated parameter [flightmode.yawMode]
2021-03-19 15:35:53,940 [DEBUG]: Updated parameter [flightmode.yawRst]
2021-03-19 15:35:53,944 [DEBUG]: Updated parameter [flightmode.stabModeRoll]
2021-03-19 15:35:53,947 [DEBUG]: Updated parameter [flightmode.stabModePitch]
2021-03-19 15:35:53,951 [DEBUG]: Updated parameter [flightmode.stabModeYaw]
2021-03-19 15:35:53,955 [DEBUG]: Updated parameter [cmdrCPPM.rateRoll]
2021-03-19 15:35:53,960 [DEBUG]: Updated parameter [cmdrCPPM.ratePitch]
2021-03-19 15:35:53,963 [DEBUG]: Updated parameter [cmdrCPPM.rateYaw]
2021-03-19 15:35:53,966 [DEBUG]: Updated parameter [cmdrCPPM.angRoll]
2021-03-19 15:35:53,970 [DEBUG]: Updated parameter [cmdrCPPM.angPitch]
2021-03-19 15:35:53,973 [DEBUG]: Updated parameter [locSrv.enRangeStreamFP32]
2021-03-19 15:35:53,977 [DEBUG]: Updated parameter [locSrv.extPosStdDev]
2021-03-19 15:35:53,980 [DEBUG]: Updated parameter [locSrv.extQuatStdDev]
2021-03-19 15:35:53,983 [DEBUG]: Updated parameter [pid_attitude.roll_kp]
2021-03-19 15:35:53,987 [DEBUG]: Updated parameter [pid_attitude.roll_ki]
2021-03-19 15:35:53,990 [DEBUG]: Updated parameter [pid_attitude.roll_kd]
2021-03-19 15:35:53,993 [DEBUG]: Updated parameter [pid_attitude.pitch_kp]
2021-03-19 15:35:53,996 [DEBUG]: Updated parameter [pid_attitude.pitch_ki]
2021-03-19 15:35:53,999 [DEBUG]: Updated parameter [pid_attitude.pitch_kd]
2021-03-19 15:35:54,003 [DEBUG]: Updated parameter [pid_attitude.yaw_kp]
2021-03-19 15:35:54,006 [DEBUG]: Updated parameter [pid_attitude.yaw_ki]
2021-03-19 15:35:54,009 [DEBUG]: Updated parameter [pid_attitude.yaw_kd]
2021-03-19 15:35:54,013 [DEBUG]: Updated parameter [pid_rate.roll_kp]
2021-03-19 15:35:54,017 [DEBUG]: Updated parameter [pid_rate.roll_ki]
2021-03-19 15:35:54,020 [DEBUG]: Updated parameter [pid_rate.roll_kd]
2021-03-19 15:35:54,024 [DEBUG]: Updated parameter [pid_rate.pitch_kp]
2021-03-19 15:35:54,028 [DEBUG]: Updated parameter [pid_rate.pitch_ki]
2021-03-19 15:35:54,032 [DEBUG]: Updated parameter [pid_rate.pitch_kd]
2021-03-19 15:35:54,036 [DEBUG]: Updated parameter [pid_rate.yaw_kp]
2021-03-19 15:35:54,041 [DEBUG]: Updated parameter [pid_rate.yaw_ki]
2021-03-19 15:35:54,045 [DEBUG]: Updated parameter [pid_rate.yaw_kd]
2021-03-19 15:35:54,049 [DEBUG]: Updated parameter [sensfusion6.kp]
2021-03-19 15:35:54,062 [DEBUG]: Updated parameter [sensfusion6.ki]
2021-03-19 15:35:54,066 [DEBUG]: Updated parameter [sensfusion6.baseZacc]
2021-03-19 15:35:54,069 [DEBUG]: Updated parameter [health.startPropTest]
2021-03-19 15:35:54,073 [DEBUG]: Updated parameter [stabilizer.estimator]
2021-03-19 15:35:54,076 [DEBUG]: Updated parameter [stabilizer.controller]
2021-03-19 15:35:54,079 [DEBUG]: Updated parameter [posEstAlt.estAlphaAsl]
2021-03-19 15:35:54,083 [DEBUG]: Updated parameter [posEstAlt.estAlphaZr]
2021-03-19 15:35:54,086 [DEBUG]: Updated parameter [posEstAlt.velFactor]
2021-03-19 15:35:54,089 [DEBUG]: Updated parameter [posEstAlt.velZAlpha]
2021-03-19 15:35:54,093 [DEBUG]: Updated parameter [posEstAlt.vAccDeadband]
2021-03-19 15:35:54,097 [DEBUG]: Updated parameter [posCtlPid.xKp]
2021-03-19 15:35:54,100 [DEBUG]: Updated parameter [posCtlPid.xKi]
2021-03-19 15:35:54,104 [DEBUG]: Updated parameter [posCtlPid.xKd]
2021-03-19 15:35:54,107 [DEBUG]: Updated parameter [posCtlPid.yKp]
2021-03-19 15:35:54,110 [DEBUG]: Updated parameter [posCtlPid.yKi]
2021-03-19 15:35:54,114 [DEBUG]: Updated parameter [posCtlPid.yKd]
2021-03-19 15:35:54,117 [DEBUG]: Updated parameter [posCtlPid.zKp]
2021-03-19 15:35:54,121 [DEBUG]: Updated parameter [posCtlPid.zKi]
2021-03-19 15:35:54,125 [DEBUG]: Updated parameter [posCtlPid.zKd]
2021-03-19 15:35:54,128 [DEBUG]: Updated parameter [posCtlPid.thrustBase]
2021-03-19 15:35:54,132 [DEBUG]: Updated parameter [posCtlPid.thrustMin]
2021-03-19 15:35:54,135 [DEBUG]: Updated parameter [posCtlPid.rpLimit]
2021-03-19 15:35:54,138 [DEBUG]: Updated parameter [posCtlPid.xyVelMax]
2021-03-19 15:35:54,142 [DEBUG]: Updated parameter [posCtlPid.zVelMax]
2021-03-19 15:35:54,146 [DEBUG]: Updated parameter [velCtlPid.vxKp]
2021-03-19 15:35:54,149 [DEBUG]: Updated parameter [velCtlPid.vxKi]
2021-03-19 15:35:54,152 [DEBUG]: Updated parameter [velCtlPid.vxKd]
2021-03-19 15:35:54,157 [DEBUG]: Updated parameter [velCtlPid.vyKp]
2021-03-19 15:35:54,160 [DEBUG]: Updated parameter [velCtlPid.vyKi]
2021-03-19 15:35:54,164 [DEBUG]: Updated parameter [velCtlPid.vyKd]
2021-03-19 15:35:54,167 [DEBUG]: Updated parameter [velCtlPid.vzKp]
2021-03-19 15:35:54,171 [DEBUG]: Updated parameter [velCtlPid.vzKi]
2021-03-19 15:35:54,174 [DEBUG]: Updated parameter [velCtlPid.vzKd]
2021-03-19 15:35:54,177 [DEBUG]: Updated parameter [controller.tiltComp]
2021-03-19 15:35:54,181 [DEBUG]: Updated parameter [ctrlMel.kp_xy]
2021-03-19 15:35:54,184 [DEBUG]: Updated parameter [ctrlMel.kd_xy]
2021-03-19 15:35:54,196 [DEBUG]: Updated parameter [ctrlMel.ki_xy]
2021-03-19 15:35:54,200 [DEBUG]: Updated parameter [ctrlMel.i_range_xy]
2021-03-19 15:35:54,203 [DEBUG]: Updated parameter [ctrlMel.kp_z]
2021-03-19 15:35:54,206 [DEBUG]: Updated parameter [ctrlMel.kd_z]
2021-03-19 15:35:54,210 [DEBUG]: Updated parameter [ctrlMel.ki_z]
2021-03-19 15:35:54,214 [DEBUG]: Updated parameter [ctrlMel.i_range_z]
2021-03-19 15:35:54,217 [DEBUG]: Updated parameter [ctrlMel.mass]
2021-03-19 15:35:54,221 [DEBUG]: Updated parameter [ctrlMel.massThrust]
2021-03-19 15:35:54,226 [DEBUG]: Updated parameter [ctrlMel.kR_xy]
2021-03-19 15:35:54,229 [DEBUG]: Updated parameter [ctrlMel.kR_z]
2021-03-19 15:35:54,233 [DEBUG]: Updated parameter [ctrlMel.kw_xy]
2021-03-19 15:35:54,236 [DEBUG]: Updated parameter [ctrlMel.kw_z]
2021-03-19 15:35:54,239 [DEBUG]: Updated parameter [ctrlMel.ki_m_xy]
2021-03-19 15:35:54,243 [DEBUG]: Updated parameter [ctrlMel.ki_m_z]
2021-03-19 15:35:54,246 [DEBUG]: Updated parameter [ctrlMel.kd_omega_rp]
2021-03-19 15:35:54,249 [DEBUG]: Updated parameter [ctrlMel.i_range_m_xy]
2021-03-19 15:35:54,253 [DEBUG]: Updated parameter [ctrlMel.i_range_m_z]
2021-03-19 15:35:54,256 [DEBUG]: Updated parameter [motorPowerSet.enable]
2021-03-19 15:35:54,259 [DEBUG]: Updated parameter [motorPowerSet.m1]
2021-03-19 15:35:54,263 [DEBUG]: Updated parameter [motorPowerSet.m2]
2021-03-19 15:35:54,266 [DEBUG]: Updated parameter [motorPowerSet.m3]
2021-03-19 15:35:54,269 [DEBUG]: Updated parameter [motorPowerSet.m4]
2021-03-19 15:35:54,272 [DEBUG]: Updated parameter [kalman.resetEstimation]
2021-03-19 15:35:54,276 [DEBUG]: Updated parameter [kalman.quadIsFlying]
2021-03-19 15:35:54,279 [DEBUG]: Updated parameter [kalman.pNAcc_xy]
2021-03-19 15:35:54,283 [DEBUG]: Updated parameter [kalman.pNAcc_z]
2021-03-19 15:35:54,286 [DEBUG]: Updated parameter [kalman.pNVel]
2021-03-19 15:35:54,290 [DEBUG]: Updated parameter [kalman.pNPos]
2021-03-19 15:35:54,293 [DEBUG]: Updated parameter [kalman.pNAtt]
2021-03-19 15:35:54,297 [DEBUG]: Updated parameter [kalman.mNBaro]
2021-03-19 15:35:54,300 [DEBUG]: Updated parameter [kalman.mNGyro_rollpitch]
2021-03-19 15:35:54,303 [DEBUG]: Updated parameter [kalman.mNGyro_yaw]
2021-03-19 15:35:54,307 [DEBUG]: Updated parameter [kalman.initialX]
2021-03-19 15:35:54,311 [DEBUG]: Updated parameter [kalman.initialY]
2021-03-19 15:35:54,316 [DEBUG]: Updated parameter [kalman.initialZ]
2021-03-19 15:35:54,329 [DEBUG]: Updated parameter [kalman.initialYaw]
2021-03-19 15:35:54,333 [DEBUG]: Updated parameter [kalman.maxPos]
2021-03-19 15:35:54,336 [DEBUG]: Updated parameter [kalman.maxVel]
2021-03-19 15:35:54,340 [DEBUG]: Updated parameter [deck.bcLedRing]
2021-03-19 15:35:54,344 [DEBUG]: Updated parameter [deck.bcBuzzer]
2021-03-19 15:35:54,347 [DEBUG]: Updated parameter [deck.bcGTGPS]
2021-03-19 15:35:54,350 [DEBUG]: Updated parameter [deck.bcCPPM]
2021-03-19 15:35:54,354 [DEBUG]: Updated parameter [deck.bcUSD]
2021-03-19 15:35:54,357 [DEBUG]: Updated parameter [deck.bcZRanger]
2021-03-19 15:35:54,360 [DEBUG]: Updated parameter [deck.bcZRanger2]
2021-03-19 15:35:54,364 [DEBUG]: Updated parameter [deck.bcDWM1000]
2021-03-19 15:35:54,368 [DEBUG]: Updated parameter [deck.bcFlow]
2021-03-19 15:35:54,371 [DEBUG]: Updated parameter [deck.bcFlow2]
2021-03-19 15:35:54,374 [DEBUG]: Updated parameter [deck.bcOA]
2021-03-19 15:35:54,378 [DEBUG]: Updated parameter [deck.bcMultiranger]
2021-03-19 15:35:54,381 [DEBUG]: Updated parameter [deck.bdLighthouse4]
2021-03-19 15:35:54,385 [DEBUG]: Updated parameter [ring.effect]
2021-03-19 15:35:54,388 [DEBUG]: Updated parameter [ring.neffect]
2021-03-19 15:35:54,392 [DEBUG]: Updated parameter [ring.solidRed]
2021-03-19 15:35:54,396 [DEBUG]: Updated parameter [ring.solidGreen]
2021-03-19 15:35:54,399 [DEBUG]: Updated parameter [ring.solidBlue]
2021-03-19 15:35:54,402 [DEBUG]: Updated parameter [ring.headlightEnable]
2021-03-19 15:35:54,406 [DEBUG]: Updated parameter [ring.glowstep]
2021-03-19 15:35:54,410 [DEBUG]: Updated parameter [ring.emptyCharge]
2021-03-19 15:35:54,413 [DEBUG]: Updated parameter [ring.fullCharge]
2021-03-19 15:35:54,417 [DEBUG]: Updated parameter [ring.fadeColor]
2021-03-19 15:35:54,420 [DEBUG]: Updated parameter [ring.fadeTime]
2021-03-19 15:35:54,423 [DEBUG]: Updated parameter [usd.logging]
2021-03-19 15:35:54,426 [DEBUG]: Updated parameter [loco.mode]
2021-03-19 15:35:54,430 [DEBUG]: Updated parameter [tdoa3.logId]
2021-03-19 15:35:54,433 [DEBUG]: Updated parameter [tdoa3.logOthrId]
2021-03-19 15:35:54,436 [DEBUG]: Updated parameter [motion.disable]
2021-03-19 15:35:54,440 [DEBUG]: Updated parameter [activeMarker.front]
2021-03-19 15:35:54,443 [DEBUG]: Updated parameter [activeMarker.back]
2021-03-19 15:35:54,446 [DEBUG]: Updated parameter [activeMarker.left]
2021-03-19 15:35:54,459 [DEBUG]: Updated parameter [activeMarker.right]
2021-03-19 15:35:54,462 [DEBUG]: Updated parameter [firmware.revision0]
2021-03-19 15:35:54,466 [DEBUG]: Updated parameter [firmware.revision1]
2021-03-19 15:35:54,470 [DEBUG]: Updated parameter [firmware.modified]
2021-03-19 15:36:03,676 [DEBUG]: Adding stateEstimate.x with id=121 and type=0x77
2021-03-19 15:36:03,676 [DEBUG]: Adding stateEstimate.y with id=122 and type=0x77
2021-03-19 15:36:03,676 [DEBUG]: Adding stateEstimate.z with id=123 and type=0x77
2021-03-19 15:36:03,676 [DEBUG]: Adding stabilizer.roll with id=117 and type=0x77
2021-03-19 15:36:03,676 [DEBUG]: Adding stabilizer.pitch with id=118 and type=0x77
2021-03-19 15:36:03,677 [DEBUG]: Adding stabilizer.yaw with id=119 and type=0x77
2021-03-19 15:36:03,677 [DEBUG]: Adding log block id 1
2021-03-19 15:36:03,677 [DEBUG]: First time block is started, add block
2021-03-19 15:36:03,681 [DEBUG]: Have successfully added id=1
2021-03-19 15:36:03,684 [INFO]: Have successfully started logging for id=1
2021-03-19 15:36:04,693 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153604.txt'

2021-03-19 15:36:05,684 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153605.txt'

2021-03-19 15:36:06,682 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153606.txt'

2021-03-19 15:36:07,539 [DEBUG]: Updated parameter [kalman.resetEstimation]
2021-03-19 15:36:07,634 [DEBUG]: Updated parameter [kalman.resetEstimation]
2021-03-19 15:36:07,681 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153607.txt'

2021-03-19 15:36:08,679 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153608.txt'

2021-03-19 15:36:09,679 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153609.txt'

2021-03-19 15:36:10,678 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153610.txt'

2021-03-19 15:36:11,685 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153611.txt'

2021-03-19 15:36:12,676 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153612.txt'

2021-03-19 15:36:13,675 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153613.txt'

2021-03-19 15:36:14,682 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153614.txt'

2021-03-19 15:36:15,674 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153615.txt'

2021-03-19 15:36:16,672 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153616.txt'

2021-03-19 15:36:17,672 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153617.txt'

2021-03-19 15:36:18,671 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153618.txt'

2021-03-19 15:36:19,670 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153619.txt'

2021-03-19 15:36:20,468 [INFO]: Take-off!
2021-03-19 15:36:20,672 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153620.txt'

2021-03-19 15:36:21,667 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153621.txt'

2021-03-19 15:36:22,666 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153622.txt'

2021-03-19 15:36:23,665 [ERROR]: Exception while doing callback on port [5]

Traceback (most recent call last):
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\__init__.py", line 399, in run
    cb.callback(pk)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 580, in _new_packet_cb
    block.unpack_log_data(logdata, timestamp)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\crazyflie\log.py", line 310, in unpack_log_data
    self.data_received_cb.call(timestamp, ret_data, self)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\cflib\utils\callbacks.py", line 55, in call
    cb(*args)
  File "C:\Users\Vicon-PC\Desktop\PROGETTO CRAZYFLIE\CrazyFlie-SdGN\own_module\crazyfun.py", line 151, in print_callback
    descriptor = open(data_file + ".txt", "x")
FileNotFoundError: [Errno 2] No such file or directory: './data_log/__20210319_153623.txt'

